DROP DATABASE IF EXISTS Instituto;

CREATE DATABASE Instituto;
USE Instituto;

CREATE TABLE usuarios(
	usuario varchar (20) NOT NULL PRIMARY KEY,
	clave varchar (44) NOT NULL,
	admin boolean NOT NULL
);
CREATE TABLE salidas(
	ID_Salidas int AUTO_INCREMENT PRIMARY KEY,
	ID_Carrera int (3),
	nombre varchar(20) NOT NULL,
	apellido varchar(20) NOT NULL,
	DNI int (9) NOT NULL,
	tipo varchar(15) NOT NULL,
    fecha date NOT NULL
	);




CREATE TABLE provincias(
	ID_Provincia int AUTO_INCREMENT PRIMARY KEY,
	nombre varchar(30)
);

CREATE TABLE localidades(
	ID_Localidad int AUTO_INCREMENT PRIMARY KEY,
	nombre varchar(20) NOT NULL,
	codigo_postal int (5) NOT NULL,
	ID_Provincia int(2),
	FOREIGN KEY (ID_Provincia) REFERENCES provincias(ID_Provincia)
);

CREATE TABLE alumnos(
	DNI int (8) NOT NULL PRIMARY KEY,
	apellido varchar(50) NOT NULL,
	nombre varchar(50) NOT NULL,
	fecha_nacimiento DATE NOT NULL,
	telefono varchar(30) NOT NULL,
	email varchar(30),
	calle varchar(30) NOT NULL,
	nro int(5) NOT NULL,
	piso int(2),
	dpto varchar(2),
	ID_Localidad int (2),
	trabaja varchar(3),
	lugar_trabajo varchar(20),
	obra_social varchar(20),
	titulo_secundario varchar(100),
	escuela_secundaria varchar(35),
	lugar_nacimiento varchar(50),
	FOREIGN KEY (ID_Localidad) REFERENCES localidades(ID_Localidad)
);

CREATE TABLE carreras(
	ID_Carrera int AUTO_INCREMENT PRIMARY KEY,
	nombre_carrera varchar(100) NOT NULL,
	reslucion varchar(15) NOT NULL,
	duracion_anios int (1) NOT NULL
);

CREATE TABLE materias(
	ID_Materia int AUTO_INCREMENT PRIMARY KEY,
	nombre_materia varchar(60),
	anio_materia int(1),
	ID_Carrera int(2),
	FOREIGN KEY (ID_Carrera) REFERENCES carreras(ID_Carrera)
);

CREATE TABLE correlativas(
	ID_Correlativa int AUTO_INCREMENT PRIMARY KEY,
	ID_Materia int (4) NOT NULL,
	ID_Materia_Correlativa int (4) NOT NULL
);

CREATE TABLE inscripciones(
	ID_Inscripcion int AUTO_INCREMENT PRIMARY KEY,
	Ciclolectivo int(4),
	ID_Carrera int(2),
	DNI int(8),
	fecha_inscripcion DATE);

CREATE TABLE profesores(
	ID_Profesor int AUTO_INCREMENT NOT NULL PRIMARY KEY,
	apellido varchar(50),
	nombre varchar(50),
	telefono varchar(20),
	email varchar(30)
);

CREATE TABLE cursadas(
	ID_Cursadas int AUTO_INCREMENT NOT NULL PRIMARY KEY,
	ciclo_lectivo int(4),
	ID_Materia int(3) NOT NULL,
	DNI int(8) NOT NULL,
	nota int (2),
	tipo varchar (3),
	ID_Profesor int(2),
	asistencia decimal,
	fecha_Aprobacion date,
	FOREIGN KEY (ID_Profesor) REFERENCES profesores(ID_Profesor),
	FOREIGN KEY (DNI) REFERENCES alumnos (DNI),
	FOREIGN KEY (ID_Materia) REFERENCES materias(ID_Materia)
);


CREATE TABLE mesasExamenes(
	ID_Examen int AUTO_INCREMENT PRIMARY KEY,
	ID_Materia int (2),
	fecha_inscripcion date,
	fecha_realizada_inscripcion date,
	ciclo_lectivo int (4),
	profesor_titular varchar(50),
	DNI int(8),
	nota int(2));


CREATE TABLE cicloLectivo(
ID_Ciclo int AUTO_INCREMENT PRIMARY KEY,
aniolectivo int (4) ,
anioCarrera int(1),
ID_Carrera int(3));

INSERT INTO cicloLectivo VALUES
(NULL,2016,1,1), 
(NULL,2017,2,1),
(NULL,2018,3,1),
(NULL,2016,1,2),
(NULL,2017,2,2),
(NULL,2018,3,2),
(NULL,2017,1,3), 
(NULL,2018,2,3),
(NULL,2019,3,3),
(NULL,2015,1,4),  
(NULL,2016,2,4),
(NULL,2017,3,4),
(NULL,2018,4,4),
(NULL,2017,1,5),  
(NULL,2018,2,5),
(NULL,2019,3,5),
(NULL,2017,1,6),  
(NULL,2018,2,6),
(NULL,2019,3,6),
(NULL,2018,1,7),  
(NULL,2019,2,7),
(NULL,2020,3,7),
(NULL,2019,1,8),
(NULL,2020,2,8),
(NULL,2021,3,8),  
(NULL,2019,1,9),
(NULL,2020,2,9),
(NULL,2021,3,9),  
(NULL,2019,1,10),
(NULL,2020,2,10),
(NULL,2021,3,10);  



INSERT INTO usuarios VALUES 
('admin',SHA1('1234'),1);



INSERT INTO carreras VALUES
(NULL,'Tecnicatura Superior en Analisis de Sistemas', '5817',3),
(NULL,'Tecnicatura Superior en Administracion Agropecuaria', '5833',3),
(NULL,'Tecnicatura Superior en Higiene y Seguridad en el trabajo', '320',3),
(NULL,'Tecnicatura Superior en Trabajo Social.','1666/06',4),
(NULL,'Tecnicatura Superior en Produccion Agricola-Ganadera.', '5818-03',3),
(NULL,'Tecnicatura Superior en Recursos Humanos','276/03',3),
(NULL,'Tecnicatura Superior en Administracion con Orientacion en Marketing', '5834-03',3),

(NULL,'Tecnicatura Superior en Comunicacion Multimedial','617/03',3),
(NULL,'Tecnicatura Superior en Administracion Financiera','277/03',3),
(NULL,'Tecnicatura Superior en Acompañamiento Teraupetico','1221/15',3);




INSERT INTO provincias VALUES
(NULL, 'Buenos Aires'),
(NULL, 'Catamarca'),
(NULL, 'Chaco'),
(NULL, 'Chubut'),
(NULL, 'Córdoba'),
(NULL, 'Corrientes'),
(NULL, 'Entre Rios'),
(NULL, 'Formosa'),
(NULL, 'Jujuy'),
(NULL, 'La Pampa'),
(NULL, 'La Rioja'),
(NULL, 'Mendoza'),
(NULL, 'Misiones'),
(NULL, 'Neuquén'),
(NULL, 'Rio Negro'),
(NULL, 'Salta'),
(NULL, 'San Juan'),
(NULL, 'San Luis'),
(NULL, 'Santa Cruz'),
(NULL, 'Santa Fe'),
(NULL, 'Santiago del Estero'),
(NULL, 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
(NULL, 'Tucumán');

INSERT INTO localidades VALUES
(NULL, 'Saladillo', '7260', 1),
(NULL, 'Del Carril', '7265', 1),
(NULL, 'Alvarez de Toledo', '7267', 1),
(NULL, 'Polvaredas', '7267', 1),
(NULL, 'Cazón', '7265', 1),
(NULL, '25 de Mayo', '6660', 1),
(NULL, 'Las flores', '7200', 1),
(NULL, 'General Alvear', '7263', 1);

INSERT INTO materias VALUES
(NULL, 'Álgebra.', '1', 1),
(NULL, 'Análisis Matematico.', '1', 1),
(NULL, 'Inglés Tecnico I.', '1', 1),
(NULL, 'Administración de las Organizaciones.', '1', 1),
(NULL, 'Metodología de la Investigación.', '1', 1),
(NULL, 'Programación I.', '1', '1'),
(NULL, 'Introducción a ls Sistemas de Información.', '1', 1),
(NULL, 'Arquitectura de Computadores.', '1', 1),
(NULL, 'Espacio de Definición Institucional (1ero).', '1', 1),
(NULL, 'Probabilidad y Estadística.', '2', 1),
(NULL, 'Análisis Matematico II.', '2', 1),
(NULL, 'Inglés Tecnico II.', '2', 1), 
(NULL, 'Sistemas de Información I.', '2', 1),
(NULL, 'Programación II.', '2', 1),
(NULL, 'Sistemas Operativos.', '2', 1),
(NULL, 'Bases de Datos.', '2', 1),
(NULL, 'Espacio de Definición Institucional (2do).', '2', 1),
(NULL, 'Investigación Operativa.', '3', 1),
(NULL, 'Economia Empresarial.', '3', 1),
(NULL, 'Teleinformática.', '3', 1),
(NULL, 'Sistemas de Información II.', '3', 1),
(NULL, 'Práctica Profesional.', '3', 1),
(NULL, 'Espacio de Definición Institucional (3ro).', '3', 1),
(NULL, 'Matematicá I.', '1', 2),
(NULL, 'Computación I.', '1', 2),
(NULL, 'Derecho.', '1', 2),
(NULL, 'Economía.', '1', 2),
(NULL, 'Contabilidad.', '1', 2),
(NULL, 'Sociologiá de la Organización.', '1', 2),
(NULL, 'Principios de Administración.', '1', 2),
(NULL, 'Metodología de la Investigación.', '1', 2),
(NULL, 'Práctica Profesional I.', '1', 2),
(NULL, 'Espacio de Definición Institucional (1ro).', '1', 2),
(NULL, 'Matematicá II.', '2', 2),
(NULL, 'Estadística.', '2', 2),
(NULL, 'Inglés I.', '2', 2),
(NULL, 'Computación II.', '2', 2),
(NULL, 'Contabilidad II.', '2', 2),
(NULL, 'Sistemas de Producción.', '2', 2),
(NULL, 'Producción Animal.', '2', 2),
(NULL, 'Producción Vegetal.', '2', 2),
(NULL, 'Derecho Comercial.', '2', 2),
(NULL, 'Administración Agropecuaria I.', '2', 2),
(NULL, 'Práctica Profesional II.', '2', 2),
(NULL, 'Espacio de Definición Institucional (2do).', '2', 2),
(NULL, 'Inglés II.', '3', 2),
(NULL, 'Gestión de Negocios Agropecuarios.', '3', 2),
(NULL, 'Evaluación de Proyectos.', '3', 2),
(NULL, 'Sociologiá Laboral.', '3', 2),
(NULL, 'Derecho Laboral.', '3', 2),
(NULL, 'Teoría y Práctica Tributaria.', '3', 2),
(NULL, 'Administración Agropecuaria II.', '3', 2),
(NULL, 'Economías Regionales.', '3', 2),
(NULL, 'Industrialización de Productos Regionales.', '3', 2),
(NULL, 'Práctica Profesional III.', '3', 2),
(NULL, 'Espacio de Definición Institucional (3ro).', '3', 2),
(NULL, 'Administracion de las organizaciones','1',3),
(NULL, 'Psicologia Laboral','1',3),
(NULL, 'Fisica I','1',3),
(NULL,'Quimica I','1',3),
(NULL,'Medios de RepresentaciónB','1',3),			
(NULL,'Medicina del Trabajo I','1',3),	
(NULL,'Seguridad I','1',3),			
(NULL,'Derecho del Trabajo','1',3),			
(NULL,'Práctica Profesionalizante I','1',3),			
(NULL,'Estadística','2',3),			
(NULL,'Física II','2',3),			
(NULL,'Química II','2',3),			
(NULL,'Ingles Técnico','2',3),			
(NULL,'Ergonomía','2',3),			
(NULL,'Seguridad II','2',3),			
(NULL,'Higiene Laboral y Medio Ambiente I','2',3),			
(NULL,'Medicina del Trabajo II','2',3),			
(NULL,'Práctica Profesionalizante II','2',3),			
(NULL,'Comunicación y Administración de Medios','3',3),			
(NULL,'Capacitación de Personal','3',3),			
(NULL,'Seguridad III','3',3),			
(NULL,'Higiene Laboral y Medio Ambiente II','3',3),			
(NULL,'Control de la Contaminación','3',3),			
(NULL,'Práctica Profesionalizante III','3',3),
(NULL,'Filosofía','1',4),
(NULL,'Psicología Evolutiva y de la Personalidad','1',4),
(NULL,'Sociología I','1',4),
(NULL,'Derecho','1',4),
(NULL,'Historia y Fundamentos del Trabajo Social.','1',4),
(NULL,'Conocimiento Institucional','1',4),
(NULL,'Metodología de la Investigación I','1',4),
(NULL,'Práctica Profesional I','1',4),
(NULL,'Espacio de Definicion Institucional (1ero)','1',4),
(NULL,'Sociología II','2',4),
(NULL,'Psicología Social','2',4),
(NULL,'Epistemología','2',4),
(NULL,'Derecho Penal y Régimen Penitenciario.','2',4),
(NULL,'Derecho de Familia','2',4),
(NULL,'Trabajo Social I','2',4),
(NULL,'Trabajo Social II','2',4),
(NULL,'Metodología de la Investigación II','2',4),
(NULL,'Práctica Profesional II','2',4),
(NULL,'Espacio de Definicion Institucional (2do)','2',4),
(NULL,'Antropología','3',4),
(NULL,'Historia Social y Política','3',4),
(NULL,'Derecho Laboral','3',4),
(NULL,'Salud Pública','3',4),
(NULL,'Inglés I','3',4),
(NULL,'Trabajo Social III','3',4),
(NULL,'Planificación y Administración','3',4),
(NULL,'Práctica Profesional III','3',4),
(NULL,'Espacio de Definicion Institucional (3ero)','3',4),
(NULL,'Economía Social','4',4),
(NULL,'Salud Mental ','4',4),
(NULL,'Inglés II','4',4),
(NULL,'Política Social ','4',4),
(NULL,'Trabajo Final de Investigación','4',4),
(NULL,'Práctica Profesional IV','4',4),
(NULL,'Espacio de Definicion Institucional (4to)','4',4),
(NULL,'Metodología de la Investigación','1',5),
(NULL,'Física Aplicada','1',5),
(NULL,'Matemática y Estadística Aplicada','1',5),
(NULL,'Agro Climatología','1',5),
(NULL,'Edafología','1',5),
(NULL,'Química Agrícola','1',5),
(NULL,'Anatomía y Fisiología Animal','1',5),
(NULL,'Morfología y Fisiología Vegetal','1',5),
(NULL,'Fitopatología','1',5),
(NULL,'Zoología Agrícola','1',5),
(NULL,'Sistemática Aplicada','1',5),
(NULL,'Práctica Profesional I','1',5),
(NULL,'Computación I','2',5),
(NULL,'Inglés Técnico','2',5),
(NULL,'Sociología Rural','2',5),
(NULL,'Forrajes y Manejo de Pasturas','2',5),
(NULL,'Genética y Mejoramiento Vegetal','2',5),
(NULL,'Manejo y conservación de Suelos','2',5),
(NULL,'Maquinaria Agrícola I','2',5),
(NULL,'Nutrición Animal','2',5),
(NULL,'Producciones Regionales','2',5),
(NULL,'Reproducción y Mejoramiento Animal','2',5),
(NULL,'Práctica Profesional II','2',5),
(NULL,'Espacio de Definicion Institucional (2do)','2',5),
(NULL,'Computación II','3',5),
(NULL,'Legislación Agraria','3',5),
(NULL,'Higiene y Seguridad Rural','3',5),
(NULL,'Gestión y Administración Rural','3',5),
(NULL,'Animales de Granja','3',5),
(NULL,'Producción de Carne y Leche','3',5),
(NULL,'Maquinaria Agrícola II','3',5),
(NULL,'Comercialización de la Producción Agropecuaria','3',5),
(NULL,'Terapéutica Vegetal','3',5),
(NULL,'Sanidad Animal','3',5),
(NULL,'Cereales y Oleaginosas','3',5),
(NULL,'Práctica Profesional III','3',5),
(NULL,'Espacio de Definicion Institucional (3ero)','3',5),
(NULL,'Matemática I','1',6),
(NULL,'Computación I','1',6),
(NULL,'Derecho','1',6),
(NULL,'Economía','1',6),
(NULL,'Contabilidad','1',6),
(NULL,'Sociología de la Organización','1',6),
(NULL,'Principios de Administración','1',6),
(NULL,'Metodología de la Investigación','1',6),
(NULL,'Marketing','1',6),
(NULL,'Espacio de Definición Institucional (1ero)','1',6),
(NULL,'Matemática II','2',6),
(NULL,'Estadística','2',6),
(NULL,'Inglés I','2',6),
(NULL,'Computación II','2',6),
(NULL,'Canales de Distribución','2',6),
(NULL,'Fundamentos de Psicología y Comportamiento del consumidor','2',6),
(NULL,'Derecho Comercial','2',6),
(NULL,'Publicidad','2',6),
(NULL,'Práctica Profesional I','2',6),
(NULL,'Espacio de Definición Institucional (2do)','2',6),
(NULL,'Ingles II','3',6),
(NULL,'Costos y Presupuestos','3',6),
(NULL,'Administración Estratégica','3',6),
(NULL,'Política y Desarrollo de Productos','3',6),
(NULL,'Comercio Internacional','3',6),
(NULL,'Política de Precios','3',6),
(NULL,'Investigación de Mercados','3',6),
(NULL,'Practica Profesional II','3',6),
(NULL,'Espacio de Definición Institucional (3ero)','3',6),
(NULL,'Matematica I','1',7),
(NULL,'Computación I','1',7),
(NULL,'Derecho','1',7),
(NULL,'Economia','1',7),
(NULL,'Contabilidad','1',7),
(NULL,'Sociología de la Organización','1',7),
(NULL,'Principios de Administración','1',7),
(NULL,'Metodologia de la investigación','1',7),
(NULL,'Administración de Personal','1',7),
(NULL,'Espacio de Definición lnstitucional (1ero)','1',7),
(NULL,'Matematica II','2',7),
(NULL,'Estadística','2',7),
(NULL,'Ingles I','2',7),
(NULL,'Computación II','2',7),
(NULL,'Seguridad Social','2',7),
(NULL,'Sicología Laboral','2',7),
(NULL,'Seguridad e Higiene del Trabajo','2',7),
(NULL,'Relaciones Laborales','2',7),
(NULL,'Derecho Laboral','2',7),
(NULL,'Práctica Profesional I ','2',7),
(NULL,'Espacio de Definición lnstitucional (2do)','2',7),
(NULL,'Ingles II','3',7),
(NULL,'Liquidación de Sueldos y Jornales','3',7),
(NULL,'Selección de Personal, Evaluación y Capacitación','3',7),
(NULL,'Dinámica Grupal','3',7),
(NULL,'Administración Estratégica de los Recursos Humanos','3',7),
(NULL,'Comunicación Organizacional','3',7),
(NULL,'Práctica Profesional II','3',7),
(NULL,'Espacio de Definición lnstitucional (3ero)','3',7),
(NULL,'Algebra','1',8),
(NULL,'Analisis Matematico I','1',8),
(NULL,'Ingles Tecnico I','1',8),
(NULL,'Administracion de las Organizaciones','1',8),
(NULL,'Metodologia de la Investigacion','1',8),
(NULL,'Introduccion a la  Programacion','1',8),
(NULL,'Fundamentos de Fotografia Imagen y Sonido','1',8),
(NULL,'Comunicacion','1',8),
(NULL,'Diseño de Informacion Conceptual','1',8),
(NULL,'Laboratorio de Medios Digitales I','1',8),
(NULL,'Probabilidad y Estadistica','2',8),
(NULL,'Analisis Matematico II','2',8),
(NULL,'Ingles Tecnico II','2',8),
(NULL,'Programacion Web','2',8),
(NULL,'Medios Audiovisuales','2',8),
(NULL,'Medios Editoriales','2',8),
(NULL,'Laboratorio de Medios Digitales II','2',8),
(NULL,'Espacio de Definicion Institucional','2',8),
(NULL,'Investigacion Operativa','3',8),
(NULL,'Economia Empresarial','3',8),
(NULL,'Ingles Tecnico III','3',8),
(NULL,'Marketing Aplicado','3',8),
(NULL,'Edicion de Video','3',8),
(NULL,'Proyecto','3',8),
(NULL,'Practica Profesional','3',8),
(NULL,'Espacio de Definicion Institucional','3',8),
(NULL,'Matematica I','1',9),
(NULL,'Computacion I','1',9),
(NULL,'Derecho','1',9),
(NULL,'Economia','1',9),
(NULL,'Contabilidad','1',9),
(NULL,'Sociologia de la organizacion','1',9),
(NULL,'Principios de Administracion','1',9),
(NULL,'Metodologia de la Investigacion','1',9),
(NULL,'Teoria y Tecnica del Seguro','1',9),
(NULL,'Espacio de Definicion Institucional','1',9),
(NULL,'Matematica II','2',9),
(NULL,'Estadistica','2',9),
(NULL,'Ingles I','2',9),
(NULL,'Computacion II','2',9),
(NULL,'Contabilidad II','2',9),
(NULL,'Matematica Financiera','2',9),
(NULL,'Administracion Financiera','2',9),
(NULL,'Comercion Internacional','2',9),
(NULL,'Derecho Comercial','2',9),
(NULL,'Practica Profesional I','2',9),
(NULL,'Espacio de Definicion Institucional','2',9),
(NULL,'Ingles II','3',9),
(NULL,'Analisis de Estudios Contables','3',9),
(NULL,'Analisis de Proyectos de Inversion','3',9),
(NULL,'Elementos del Mercado Financiero','3',9),
(NULL,'Costos y Presupuesto','3',9),
(NULL,'Tecnica y Contabilidad Bancaria','3',9),
(NULL,'Practica Profesional II','3',9),
(NULL,'Espacio de Definicion Institucional','3',9),
(NULL,'Salud Publica y Salud Mental','1',10),
(NULL,' Contextualizacion del Campo Profesional del Acompañamiento Terapeutico','1',10),
(NULL,'Principios Medicos y de Psicofarmacologia ','1',10),
(NULL,'Fundamentos de Psicologia General y de Intervencion Sociocomunitaria ','1',10),
(NULL,'Psicologia de los Ciclos Vitales ','1',10),
(NULL,' Psicopatologia','1',10),
(NULL,' Modalidades de Intervencion en el Acompañamiento Terapeutico','1',10),
(NULL,'Investigacion en Salud','2',10),
(NULL,'Modeo de Ocupacion Humana','2',10),
(NULL,'Etica ','2',10),
(NULL,' Acompañamiento Terapeutico','2',10),
(NULL,' Psicologia de Grupos','2',10),
(NULL,'Sistemas Familiares ','2',10),
(NULL,' Psicofarmacologia','2',10),
(NULL,'Ingles','3',10),
(NULL,'Organizacion y Gestion de los Servicios de Salud Mental','3',10),
(NULL,'Intervencion Comunitaria y Recursos Sociales','3',10),
(NULL,'Acompañamiento Terapeutico en la Niñes y Adolescencia','3',10),
(NULL,'Acompañamiento Terapeutico del Adulto y Adulto Mayor','3',10);



INSERT INTO correlativas VALUES
(NULL, 10, '1'),
(NULL, 10, '2'),
(NULL, 11, '2'),
(NULL, 12, '3'),
(NULL, 13, '7'),
(NULL, 13, '4'),
(NULL, 14, '6'),
(NULL, 15, '8'),
(NULL, 16, '6'),
(NULL, 18, '10'),
(NULL, 18, '12'),
(NULL, 18, '14'),
(NULL, 19, '13'),
(NULL, 20, '15'),
(NULL, 21, '13'),
(NULL, 22, '5'),
(NULL, 22, '14'),
(NULL, 22, '16'),
(NULL, 22, '13'),
(NULL, 34, '24'),
(NULL, 35, '24'),
(NULL, 37, '25'),
(NULL, 46, '36'),
(NULL, 38, '28'),
(NULL, 43, '30'),
(NULL, 52, '43'),
(NULL, 44, '24'),
(NULL, 44, '25'),
(NULL, 44, '26'),
(NULL, 44, '27'),
(NULL, 44, '28'),
(NULL, 44, '29'),
(NULL, 44, '30'),
(NULL, 44, '31'),
(NULL, 44, '32'),
(NULL, 44, '33'),
(NULL, 55, '34'),
(NULL, 55, '35'),
(NULL, 55, '36'),
(NULL, 55, '37'),
(NULL, 55, '38'),
(NULL, 55, '39'),
(NULL, 55, '40'),
(NULL, 55, '41'),
(NULL, 55, '42'),
(NULL, 55, '43'),
(NULL, 55, '44'),
(NULL, 55, '45'),
(NULL, 67,'59'),
(NULL, 68,'60'),
(NULL, 73,'62'),
(NULL, 70,'62'),
(NULL, 76,'58'),
(NULL, 71,'63'),
(NULL, 75,'57'),
(NULL, 76,'58'),
(NULL, 77,'71'),
(NULL, 78,'72'),
(NULL, 79,'72'),
(NULL, 95,'85'),
(NULL, 95,'86'),
(NULL, 95,'87'),
(NULL, 96,'85'),
(NULL, 96,'86'),
(NULL, 96,'87'),
(NULL, 97,'87'),
(NULL, 90,'83'),
(NULL, 91,'82'),
(NULL, 92,'81'),
(NULL, 93,'84'),
(NULL, 94,'84'),
(NULL, 98,'85'),
(NULL, 98,'86'),
(NULL, 98,'87'),
(NULL, 98,'88'),
(NULL, 105,'95'),
(NULL, 105,'97'),
(NULL, 106,'95'),
(NULL, 106,'96'),
(NULL, 106,'97'),
(NULL, 100,'90'),
(NULL, 101,'90'),
(NULL, 102,'84'),
(NULL, 107,'95'),
(NULL, 107,'96'),
(NULL, 107,'97'),
(NULL, 107,'98'),
(NULL, 112,'106'),
(NULL, 112,'101'),
(NULL, 110,'91'),
(NULL, 110,'103'),
(NULL, 114,'105'),
(NULL, 114,'107'),
(NULL, 114,'106'),
(NULL, 113,'81'),
(NULL, 113,'82'),
(NULL, 113,'83'),
(NULL, 113,'84'),
(NULL, 113,'85'),
(NULL, 113,'86'),
(NULL, 113,'87'),
(NULL, 113,'88'),
(NULL, 113,'89'),
(NULL, 113,'90'),
(NULL, 113,'91'),
(NULL, 113,'92'),
(NULL, 113,'93'),
(NULL, 113,'94'),
(NULL, 113,'95'),
(NULL, 113,'96'),
(NULL, 113,'97'),
(NULL, 113,'98'),
(NULL, 113,'99'),
(NULL, 113,'100'),
(NULL, 113,'101'),
(NULL, 113,'102'),
(NULL, 113,'103'),
(NULL, 113,'104'),
(NULL, 113,'105'),
(NULL, 113,'106'),
(NULL, 113,'107'),
(NULL, 113,'108'),
(NULL, 113,'109'),
(NULL, 113,'110'),
(NULL, 113,'111'),
(NULL, 113,'112'),
(NULL, 113,'114'),
(NULL, 113,'115'),
(NULL, 131,'123'),
(NULL, 131,'126'),
(NULL, 132,'123'),
(NULL, 132,'121'),
(NULL, 133,'119'),
(NULL, 133,'120'),
(NULL, 133,'121'),
(NULL, 134,'117'),
(NULL, 135,'135'),
(NULL, 135,'121'),
(NULL, 137,'122'),
(NULL, 138,'116'),
(NULL, 138,'117'),
(NULL, 138,'118'),
(NULL, 138,'119'),
(NULL, 138,'120'),
(NULL, 138,'121'),
(NULL, 138,'122'),
(NULL, 138,'123'),
(NULL, 138,'124'),
(NULL, 138,'125'),
(NULL, 138,'126'),
(NULL, 138,'127'),
(NULL, 140,'128'),
(NULL, 143,'118'),
(NULL, 143,'128'),
(NULL, 144,'135'),
(NULL, 145,'135'),
(NULL, 145,'131'),
(NULL, 146,'134'),
(NULL, 148,'124'),
(NULL, 148,'125'),
(NULL, 148,'126'),
(NULL, 149,'122'),
(NULL, 150,'133'),
(NULL, 150,'123'),
(NULL, 150,'124'),
(NULL, 150,'125'),
(NULL, 151,'128'),
(NULL, 151,'129'),
(NULL, 151,'130'),
(NULL, 151,'131'),
(NULL, 151,'132'),
(NULL, 151,'133'),
(NULL, 151,'134'),
(NULL, 151,'135'),
(NULL, 151,'136'),
(NULL, 151,'137'),
(NULL, 151,'138'),
(NULL, 151,'139'),
(NULL, 166,'154'),
(NULL, 164,'153'),
(NULL, 163,'153'),
(NULL, 167,'161'),
(NULL, 169,'155'),
(NULL, 173,'165'),
(NULL, 175,'159'),
(NULL, 177,'156'),
(NULL, 174,'157'),
(NULL, 179,'160'),
(NULL, 179,'156'),
(NULL, 179,'161'),
(NULL, 178,'161'),
(NULL, 176,'161'),
(NULL, 171,'153'),
(NULL, 171,'154'),
(NULL, 171,'155'),
(NULL, 171,'156'),
(NULL, 171,'157'),
(NULL, 171,'158'),
(NULL, 171,'159'),
(NULL, 171,'160'),
(NULL, 171,'161'),
(NULL, 171,'162'),
(NULL, 180,'163'),
(NULL, 180,'164'),
(NULL, 180,'165'),
(NULL, 180,'166'),
(NULL, 180,'167'),
(NULL, 180,'168'),
(NULL, 180,'169'),
(NULL, 180,'170'),
(NULL, 180,'171'),
(NULL, 180,'172'),
(NULL, 195,'183'),
(NULL, 193,'182'),
(NULL, 192,'182'),
(NULL, 200,'184'),
(NULL, 203,	'194'),
(NULL, 197,	'190'),
(NULL, 199,	'184'),
(NULL, 204,	'196'),
(NULL, 206,	'197'),
(NULL, 207,	'199'),
(NULL, 208,	'197'),
(NULL, 201,	'182'),
(NULL, 201,	'183'),
(NULL, 201,	'184'),
(NULL, 201,	'185'),
(NULL, 201,	'186'),
(NULL, 201,	'187'),
(NULL, 201, '188'),
(NULL, 201,	'189'),
(NULL, 201,	'190'),
(NULL, 201,	'191'),
(NULL, 209,	'192'),
(NULL, 209,	'193'),
(NULL, 209,	'194'),
(NULL, 209,	'195'),
(NULL, 209,	'196'),
(NULL, 209,	'197'),
(NULL, 209,	'198'),
(NULL, 209,	'199'),
(NULL, 209,	'200'),
(NULL, 209,	'201'),
(NULL, 209,	'202');

INSERT INTO profesores VALUES
(NULL,'Massa','Ana Laura','',''), 
(NULL,'Pensa','Andrea','' ,''), 
(NULL,'Perdomo','Ariel', '',''), 
(NULL,'Saggion','Betiana','' ,''), 
(NULL,'Avinceta','César Ramiro ','' ,''), 
(NULL,'Álvarez','Clide','' ,''), 
(NULL,'Bonfiglio','Daniela','' ,''), 
(NULL,'Galbusera','Diego','' ,''), 
(NULL,'Rosso Vich','Eduardo','' ,''), 
(NULL,'Santilli','Eduardo','' ,''), 
(NULL,'Prado','Fabiana','' ,''), 
(NULL,'Mori','Fernanda','' ,''), 
(NULL,'Garcia Llorente','Fernando', '',''), 
(NULL,'Zarragoicoechea','Fernando','' ,''), 
(NULL,'Fernandez Carrillo','Francisco José','' ,''), 
(NULL,'Brassesco','Gisela','' ,''), 
(NULL,'Candia','Guillermo','' ,''), 
(NULL,'Candia','Ivana Almendros ','' ,''), 
(NULL,'Coronel','Ivana','' ,''), 
(NULL,'García','Juan', '',''), 
(NULL,'Vaccarini','Laura','' ,''), 
(NULL,'Colás','Leticia','' ,''), 
(NULL,'Cabal','Lucia', '',''), 
(NULL,'Zubiri','Marcos','' ,''), 
(NULL,'Alvarez','María Inés','' ,''), 
(NULL,'Acosta','Maria Laura','' ,''), 
(NULL,'Nuñez','Maria Laura ','' ,''), 
(NULL,'Mazza','Mariana','' ,''), 
(NULL,'Farace','Mariano', '',''), 
(NULL,'Ardiles','Maricel','' ,''), 
(NULL,'Morena','Marina','' ,''), 
(NULL,'Serna','Marisol','' ,''), 
(NULL,'Melli','Marta ', '',''), 
(NULL,'Renzi','Martin','' ,''), 
(NULL,'Tiseira','Martin ','' ,''), 
(NULL,'Saizar','Pablo', '',''), 
(NULL,'Goyeneche','Paulina ','' ,''), 
(NULL,'Spinelli','Rosana','' ,''), 
(NULL,'Spinelli','Silvana', '',''), 
(NULL,'Krupitzky','Silvina ','' ,''), 
(NULL,'Garbarino','Silvio','' ,''), 
(NULL,'Picone','Vanesa', '',''), 
(NULL,'Dichiara','Vanesa Romina','' ,''), 
(NULL,'Gallo','Vanina', '',''), 
(NULL,'Pace','Viviana', '',''); 